# Generated by Django 3.0.3 on 2020-02-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_auto_20200228_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='family',
            name='description',
            field=models.TextField(blank=True, help_text='Optional - what is amazing about you folks?'),
        ),
        migrations.AlterField(
            model_name='family',
            name='members',
            field=models.ManyToManyField(to='Authentication.Member'),
        ),
    ]
