# Generated by Django 3.0.3 on 2020-02-28 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_auto_20200228_1940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='name',
            new_name='member',
        ),
    ]
