# Generated by Django 3.0.3 on 2020-02-28 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0005_auto_20200228_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='family',
            name='members',
            field=models.ManyToManyField(to='Authentication.Member'),
        ),
    ]
