# Generated by Django 3.0.3 on 2020-03-19 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0007_auto_20200316_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='password',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
