# Generated by Django 3.0.3 on 2020-03-01 13:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('desc', models.TextField()),
                ('day', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(32), django.core.validators.MinValueValidator(1)])),
            ],
        ),
    ]
