# Generated by Django 3.0.3 on 2020-03-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logged', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='title',
        ),
        migrations.AddField(
            model_name='event',
            name='month',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='occasion',
            field=models.CharField(default='None', max_length=64),
        ),
        migrations.AlterField(
            model_name='event',
            name='day',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='desc',
            field=models.TextField(blank=True),
        ),
    ]
