# Generated by Django 3.0.3 on 2020-03-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logged', '0002_auto_20200301_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='day',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='month',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
