# Generated by Django 3.0.3 on 2020-03-01 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logged', '0004_event_who'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='who',
            new_name='author',
        ),
    ]
