# Generated by Django 3.0.3 on 2020-03-01 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logged', '0006_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
