# Generated by Django 3.0.3 on 2020-03-02 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logged', '0007_remove_post_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='None', max_length=256)),
                ('title', models.CharField(default='None', max_length=256)),
                ('desc', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(upload_to='media/images')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
