# Generated by Django 3.0.3 on 2020-03-02 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logged', '0008_auto_20200302_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(blank=True, default='None', max_length=256),
        ),
    ]
