# Generated by Django 3.0.3 on 2020-03-02 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logged', '0009_auto_20200302_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='desc',
            field=models.TextField(blank=True, help_text='Description, optional'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(blank=True, default='None', help_text='Title, optional', max_length=256),
        ),
    ]
