# Generated by Django 3.0.3 on 2020-03-02 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logged', '0011_auto_20200302_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='./'),
        ),
    ]
