# Generated by Django 3.0.3 on 2020-03-16 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logged', '0014_comment_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='None', max_length=256)),
                ('phone_number', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
